<a href="https://colab.research.google.com/github/Neharin-tijo/Basic-Python-for-Machine-Learning/blob/main/Basic_Python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python Basics**

In [2]:
# printing a string
print("Hello,Python!")
print("hi")

Hello,Python!
hi


>Variables

In [2]:
# defining a variable : In python there is no need to mention the datatype

var1=10      # An integer assignment
var2=3.146   # A floating point
var3="Hello" # A string
print(var1,' ',var2,' ',var3) 

10   3.146   Hello


In [3]:
pi=3.14
print("Value of pi is",pi)

Value of pi is 3.14


>Assignment

In [3]:
# Assigning same value to multiple variables

var1=var2=var3=1
print(var1,' ',var2,' ',var3,' ')

# Assigning different values to variables in a single expression

var1,var2,var3=1,2.5,"John"
print(var1,' ',var2,' ',var3)

# Note: commas can be used for multi-assignments

1   1   1  
1   2.5   John


# Slicing

In [4]:
# String operations

str="Hello World!"   # A string
print(str)           # prints complete string
print(str[0])        # prints first character of string
print(str[2:5])      # prints characters starting from 3rd to 5th element
print(str[2:])       # prints string starting from 3rd character
print(str[:2])       
print(str * 2)       # prints string 2 times
print(str + "TEST")  # print concatenated string

Hello World!
H
llo
llo World!
He
Hello World!Hello World!
Hello World!TEST


# Data Types

In [5]:
# Python Lists

list = ['abcd',786,2.23,'john',70.2]  # A list
tuple = ('abcd',786,2.23,'john',70.2) # A tuple. Tuples are immutable, i.e. cannot be edit later

print(list)        # prints complete list 
print(list[0])     # prints 1st element of list
print(tuple[1:3])  # prints elements starting from 2nd till 3rd

list[0]='fgg'

['abcd', 786, 2.23, 'john', 70.2]
abcd
(786, 2.23)


# Conditioning and looping

In [10]:
# square of even numbers

for i in range(0,10):
  if i % 2 == 0:
    print("Square of",i,"is",i*i)
  else:
    print(i,"is an odd number")

Square of 0 is 0
1 is an odd number
Square of 2 is 4
3 is an odd number
Square of 4 is 16
5 is an odd number
Square of 6 is 36
7 is an odd number
Square of 8 is 64
9 is an odd number


# Built-in functions

In [12]:
print("Sum of array:",sum([1,2,3,4]))
print("Length of array:",len([1,2,3,4]))
print("Absolute value:",abs(-1234))
print("Round value:",round(1.223))

import math as mt    # importing a package
print("Log value:",mt.log(10))

Sum of array: 10
Length of array: 4
Absolute value: 1234
Round value: 1
Log value: 2.302585092994046


#Functions

In [1]:
def area(length,width):
  return length*width
are=area(10,20)
print("Area of rectangle:",are)

Area of rectangle: 200


#Broadcasting

*   Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes
#NumPy
*Numpy is the fundamental package for numerical computing with Python. It contains among other things:
*  a powerful N-dimensional array object
*  sophisticated (broadcasting) functions
*  tools for integrating C/C++ and Fortran code
*  useful linear algebra, Fourier transform, and random number capabilities
*  Details of numpy   



In [4]:
import numpy as np   # Importing libraries

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
print("Matrix A\n", a)
print("Matrix B\n", b)
print("Regular matrix addition A+B\n", a + b)
print("Addition using Broadcasting A+5\n", a + 5)

Matrix A
 [0 1 2]
Matrix B
 [5 5 5]
Regular matrix addition A+B
 [5 6 7]
Addition using Broadcasting A+5
 [5 6 7]


#Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when
1.   they are equal, or
2.   one of them is 1

In [5]:
# Lets go for a 2D matrix
c = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
d = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
e = np.array([1, 2, 3])
print("Matrix C\n", c)
print("Matrix D\n", d)
print("Matrix E\n", e)
print("Regular matrix addition C+D\n", c + d)
print("Addition using Broadcasting C+E\n", c + e)

Matrix C
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix D
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Matrix E
 [1 2 3]
Regular matrix addition C+D
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
Addition using Broadcasting C+E
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [6]:
M = np.ones((3, 3))
print("Matrix M:\n",M)

Matrix M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print("Dimension of M:",M.shape)
print("Dimension od a:",a.shape)
print("Addition using Broadcasting")
print(M+a)
#Broadcasting of array with matrix

Dimension of M: (3, 3)
Dimension od a: (3,)
Addition using Broadcasting
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


#All in one program

In [8]:
# Importing libraries
import timeit

# Usage of builtin functions
start = timeit.default_timer()   

# Defining a list
array_list = [10,11,15,19,21,32]      
array_np_list = []

# Print the list
print("Original List",array_list,"\n")   

# Defining a function
def prime(num):      
    if num > 1:     
        
        # check for factors
        # Iterating a range of numbers
        for i in range(2,num):    
            if (num % i) == 0:
                
                # Appending data to list
                array_np_list.append(num)           
                print(num,"is not a prime number (",i,"times",num//i,"is",num,")")
                
                # Terminating a loop run
                break         
        else:
            print(num,"is a prime number")
            
# Iterating a list
for item in array_list:
    
    # Calling a function
    prime(item)         

print("\nNon-prime List",array_np_list,"\n")

end = timeit.default_timer()

# Computing running time
print("Time Taken to run the program:",end - start, "seconds")       

Original List [10, 11, 15, 19, 21, 32] 

10 is not a prime number ( 2 times 5 is 10 )
11 is a prime number
15 is not a prime number ( 3 times 5 is 15 )
19 is a prime number
21 is not a prime number ( 3 times 7 is 21 )
32 is not a prime number ( 2 times 16 is 32 )

Non-prime List [10, 15, 21, 32] 

Time Taken to run the program: 0.006007200000112789 seconds


Note:
*   Python is a procedural Language
*   Two versions of Python 2 vs 3
*   No braces. i.e. indentation
*   No need to explicitly mention data type